
Exceptions provide a way to react to exceptional circumstances (like runtime errors) in programs by transferring control to special functions called <i>handlers</i>.<br>
<br>
To catch exceptions, a portion of code is placed under exception inspection. This is done by enclosing that portion of code in a <i>try-block</i>. When an exceptional circumstance arises within that block, an exception is thrown that transfers the control to the exception handler. If no exception is thrown, the code continues normally and all handlers are ignored.<br>
<br>
An exception is thrown by using the <code>throw</code> keyword from inside the <code>try</code> block. Exception handlers are declared with the keyword <code>catch</code>, which must be placed immediately after the <code>try</code> block:<br>
<br>
<div class="auto"><table class="split"><tr><td class="rownum"><pre><code>1<br>2<br>3<br>4<br>5<br>6<br>7<br>8<br>9<br>10<br>11<br>12<br>13<br>14<br>15<br></code></pre></td>
<td class="source"><pre><code><cite>// exceptions</cite>
<dfn>#include &lt;iostream&gt;</dfn>
<var>using</var> <var>namespace</var> std;

<var>int</var> main () {
  <var>try</var>
  {
    <var>throw</var> 20;
  }
  <var>catch</var> (<var>int</var> e)
  {
    cout &lt;&lt; <kbd>"An exception occurred. Exception Nr. "</kbd> &lt;&lt; e &lt;&lt; <kbd>'\n'</kbd>;
  }
  <var>return</var> 0;
}</code></pre></td>
<td class="output"><pre><samp>An exception occurred. Exception Nr. 20</samp></pre></td></tr></table></div>
<br>
<br>
The code under exception handling is enclosed in a <code>try</code> block. In this example this code simply throws an exception:<br>
<br>
<div class="auto"><table class="snippet"><tr><td class="rownum"><pre><code>&nbsp;</code></pre></td>
<td class="source"><pre><code><var>throw</var> 20;</code></pre></td></tr></table></div>
<br>
<br>
A <code>throw</code> expression accepts one parameter (in this case the integer value <code>20</code>), which is passed as an argument to the exception handler.<br>
<br>
The exception handler is declared with the <code>catch</code> keyword immediately after the closing brace of the <code>try</code> block. The syntax for <code>catch</code> is similar to a regular function with one parameter. The type of this parameter is very important, since the type of the argument passed by the <code>throw</code> expression is checked against it, and only in the case they match, the exception is caught by that handler.<br>
<br>
Multiple handlers (i.e., <code>catch</code> expressions) can be chained; each one with a different parameter type. Only the handler whose argument type matches the type of the exception specified in the <code>throw</code> statement is executed.<br>
<br>
If an ellipsis (<code>...</code>) is used as the parameter of <code>catch</code>, that handler will catch any exception no matter what the type of the exception thrown. This can be used as a default handler that catches all exceptions not caught by other handlers:<br>
<br>
<div class="auto"><table class="snippet"><tr><td class="rownum"><pre><code>1<br>2<br>3<br>4<br>5<br>6<br></code></pre></td>
<td class="source"><pre><code><var>try</var> {
  <cite>// code here</cite>
}
<var>catch</var> (<var>int</var> param) { cout &lt;&lt; <kbd>"int exception"</kbd>; }
<var>catch</var> (<var>char</var> param) { cout &lt;&lt; <kbd>"char exception"</kbd>; }
<var>catch</var> (...) { cout &lt;&lt; <kbd>"default exception"</kbd>; }</code></pre></td></tr></table></div>
<br>
<br>
In this case, the last handler would catch any exception thrown of a type that is neither <code>int</code> nor <code>char</code>.<br>
<br>
After an exception has been handled the program, execution resumes after the <i>try-catch</i> block, not after the <code>throw</code> statement!.<br>
<br>
It is also possible to nest <code>try-catch</code> blocks within more external <code>try</code> blocks. In these cases, we have the possibility that an internal <code>catch</code> block forwards the exception to its external level. This is done with the expression <code>throw;</code> with no arguments. For example: <br>
<br>
<div class="auto"><table class="snippet"><tr><td class="rownum"><pre><code>1<br>2<br>3<br>4<br>5<br>6<br>7<br>8<br>9<br>10<br>11<br></code></pre></td>
<td class="source"><pre><code><var>try</var> {
  <var>try</var> {
      <cite>// code here</cite>
  }
  <var>catch</var> (<var>int</var> n) {
      <var>throw</var>;
  }
}
<var>catch</var> (...) {
  cout &lt;&lt; <kbd>"Exception occurred"</kbd>;
}</code></pre></td></tr></table></div>
<br>
